AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 3

Resources:

    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: quackbot-gsheet-to-json
            Description: Turns Google sheets into JSON files on S3, by Ryan Pitts
            Role: arn:aws:iam::844030562261:role/quackbot-lambda-gsheets-json-executor
            CodeUri: app/
            Handler: app.lambda_handler
            Runtime: python2.7

Outputs:

    MyFunction:
      Description: "Your Function ARN"
      Value: !GetAtt MyFunction.Arn